BINARIES_DIRECTORY=/usr/local/bin/
EXECUTABLE_NAME=gitfame
EXECUTABLE_PATH=$(BINARIES_DIRECTORY)$(EXECUTABLE_NAME)

install:
	cp -rf $(EXECUTABLE_NAME) $(EXECUTABLE_PATH)
	chmod +x $(EXECUTABLE_PATH)

uninstall:
	rm -f $(BINARIES_DIRECTORY)$(EXECUTABLE_NAME)
